services:
  money-flow:
    build: .
    restart: unless-stopped
    env_file: .env
    network_mode: host
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.money-flow.rule=Host(`mf.fasolo.tech`)"
      - "traefik.http.routers.money-flow.entrypoints=websecure"
      - "traefik.http.routers.money-flow.tls.certresolver=letsencrypt"
      - "traefik.http.services.money-flow.loadbalancer.server.port=3000"
